# Generated by Django 5.2 on 2025-05-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('area', models.FloatField(help_text='Powierzchnia w m²')),
                ('property_type', models.CharField(choices=[('flat', 'Mieszkanie'), ('house', 'Dom'), ('commercial', 'Lokal usługowy')], max_length=20)),
                ('rooms', models.PositiveIntegerField(default=1, help_text='Liczba pokoi')),
                ('description', models.TextField(blank=True)),
                ('is_furnished', models.BooleanField(default=False, help_text='Czy umeblowane?')),
                ('is_rented', models.BooleanField(default=False, help_text='Czy wynajmowane?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
