# Generated by Django 5.2 on 2025-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
