# Generated by Django 5.2 on 2025-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Opis płatności (opcjonalnie)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.CharField(default='Czynsz', help_text="Tytuł płatności, np. 'Czynsz maj 2025'", max_length=200),
            preserve_default=False,
        ),
    ]
