# Generated by Django 5.2 on 2025-05-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_populate_invoice_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
